services:
  assistant:
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
    volumes:
      - db:/usr/src/app/db
volumes:
  db: